    LOCAL 1800H ; LOCATION THAT THE KARNAL SETS UP THE MAGIC BOOT-PAPER-STRIP
                ; CODE OF THE FIRST 1K (4CM) OF THE PAPER TAPE

    ;---------LOGICALLY-----------
    SP_RH EQU 8000H ; SP HIGH
    SP_RL EQU 8001H ; SP LOW
    BL_RG EQU 8002H ; LINK FLAG
    RET_R EQU 8003H ; RET REG
    DBG_R EQU 8004H ; DBG REG

    ;----------VIDEO------------
    VDFNT EQU 0D078H; D078H-D0F8H VIRT TO LED LIST TABLE
    VDPHY EQU 0D000H; D000H-D03BH LED TO LED LIST CON, D000H-D0F6H IN 19X13 HSV8
    VVIRT EQU 0D03CH; D03CH-D077H VIRT TO LED LIST CON

    ; DEFAULT VALUES OF THAT ATTRIBUTES GIVE AS RESULT A
    ; TEXT SCHEME LIKE C64 BASIC ROM REPL
    VDBGC EQU 0D0F9H; D0F9H BG COLOR, 70=DEFAULT
    VTXTC EQU 0D0FAH; D0FAH TEXT & BG2 COLOR, 75=DEFAULT
    VTXTB EQU 0D0FBH; D0FBH TEXT & BG2 BRIGH, 100=DEFAULT
    VDONS EQU 0D0FCH; D0FCH ON & BG2 SATURATION, 30=DEFAULT
    VOFFT EQU 0D0FDH; D0FDH OFF TRANSPARENCY, 70=DEFAULT
    VMODE EQU 0D0FEH; D0FEH VIDEO MODE, DEFAULT=0 (TEXT, 1=19X13 8BIT HSV 
                    ; 3 BITS FOR HUE, 3 BITS FOR BRIGHT, 2 BITS FOR SATURATION)

START:
.UPA:
    STR $VMODE, $1 ; VIDEOMODE
    PG3 $VDPHY.H
    CHA $VDPHY.L ; THE SPECIAL FOR THE REPRESENTABLE KEYS
    CPY ; COPY VALUE OF ACUMULATOR TO Y
    STD ; SET FLAG OF DIRECTION FOR INCREMENTS
    CHB $(19*13-1) ; NUMBER OF ASCIIS
.LO3P:
    SSA %Y ; STORE TO VRAM
    CPX ; SAVE AT X
    MVA %B ; MOVE B VALUE
    CHC $1 ; COMPARE
    TSA %C ; TEST FOR COMP
    ZRC ; CLEAR FLAG
    SBB %C ; BECAUSE THE VALUE OF C IS SETTED USE IT FOR OPTIMIZE
    CPB ; COPY ACUMULATOR TO B
    MVA %X ; LOAD FROM X
    CHC $1 ; INCREMENTATION
    ADC %C ; ADITION
    LDC $2 ; LOAD NOT EQUAL FLAG TO COMP FLAG
    PAG $.LO3P.H ; SET PAGE
    BCC $.LO3P.L ; REPEAT
    STC ; ALWAYS JUMPS
.LT:
    PAG $.LT.H ; LOOP PAGE
    BCC $.LT.L ; REPEAT LOOP