    LOCAL 1800H ; LOCATION THAT THE KARNAL SETS UP THE MAGIC BOOT-PAPER-STRIP
                ; CODE OF THE FIRST 1K (4CM) OF THE PAPER TAPE

; INSTRUCTIONS THAT THE 
; CALCULATOR INTERCEPTS
DEF SIN (15H, 00H) ; A = SIN A
DEF COS (15H, 01H) ; A = COS A

START:
    STC ; SET COMP FLAG
    STR $8002H ; LINK IN NEXT BRANCH
    JIC $0E010H ; SWITCH TO GRAPICHAL MODE
    CHA $10 ; REGISTER TRAP
    CPX ; COPY TO X
    CHA $10 ; REG TRAP
    CPY ; COPY TO Y
    CHA $25 ; A COLOR
    STR $8002H ; LINK IN NEXT BRANCH
    STC ; SET COMP FLAG
    JIC $0E00CH ; DRAW PIXEL
HANG:
    STC ; SET COMP FLAG
    JIC $HANG ; HANG