    ; KARNAL OS 0.1.0
    LOCAL 0C000H ; FIRMWARE STARTS IN C000H 
                 ; (16K ROM BEGINS EHBEBEBBE)
    
    ; CPU MAX ACCESS MEMORY LIMIT MAX IS
    ; 64K AND THE BAIOS IS IN DA EHBEHEB
    ; END OF FILE I SAY RAM, XIGL SIGA WE
    ;
    ; THE TARGET MACHINE FOR THIS FILTH IS
    ; A MACHINE. WELL WELL, IS A PC THAT HAS
    ; A DISPLAY SCREEN LIKE THE LCD MONO
    ; CALCS YES, THESE THAN IF YOU LOOK FROM
    ; A PERFECT ANGLE YOU READ THAT SAYS '8888888'
    ; HEHEHE

    ; ------------------------
    ;        EQUATES         :
    ; ------------------------

    ;---------LOGICALLY-----------
    SP_RH EQU 8000H ; SP HIGH
    SP_RL EQU 8001H ; SP LOW
    BL_RG EQU 8002H ; LINK FLAG
    RET_R EQU 8003H ; RET REG
    DBG_R EQU 8004H ; DBG REG

    ;----------DEVICES------------
    DEV_A EQU 8066H ; SNDCARD FREQ
    DEV_B EQU 8024H ; CREATES A MIRROR AT B000H-BFFF
                    ; ANY OFFSET OF PG(100H+P2,00H)
    MEM_B EQU 0B000H; MIRROR IN THE DIRECTION

    ;----------RAM1 MAP------------
    VDMEM EQU 00B8H ; 1B800H-1BFFFH

    ;----------VIDEO------------
    VDFNT EQU 080H  ; 1B880H-1B8FFH VIRT TO LED LIST TABLE
    VDPHY EQU 000H  ; 1B800H-1B83BH LED TO LED LIST CON
    VVIRT EQU 03CH  ; 1B83CH-1B877H VIRT TO LED LIST CON

    ; DEFAULT VALUES OF THAT ATTRIBUTES GIVE AS RESULT A
    ; TEXT SCHEME LIKE C64 BASIC ROM REPL
    VDBGC EQU 100H  ; 1B900H BG COLOR, 70=DEFAULT
    VTXTC EQU 101H  ; 1B901H TEXT & BG2 COLOR, 75=DEFAULT
    VTXTB EQU 102H  ; 1B902H TEXT & BG2 BRIGH, 100=DEFAULT
    VDONS EQU 103H  ; 1B903H ON & BG2 SATURATION, 30=DEFAULT
    VOFFT EQU 104H  ; 1B904H OFF TRANSPARENCY, 70=DEFAULT

    ; THE KEYBOARD DRIVER IT IS SOLDERED TO THE SCREEN
    ; SO THERE SHARE ADDRESSING SPACE AND IS IMPOSSIBLE
    ; TO SPLIT THE KEYBOARD FROM THE SCREEN
    KYBRD EQU 200H  ; 1BA00H KEYBOARD READ

    ; VECTORS AT FIRMWARE DATA STARTS EACH VECTOR
    ; HAS A LENGHT OF 4 BYTES (TWO INSTRUCTIONS)

    JIC $VIDEO_TTY  ; C000H :: tty write
    JIC $ATOI       ; C004H :: atoi

    ; ------------------------
    ;        128B STACK     :
    ; ------------------------
STACK: RSV 128
TOS:

    ; ------------------------
    ;       LETTER MAP      :
    ; ------------------------
MAP:
    DB 77H,24H,5DH,6DH,2EH,5DH,7BH  ;0-6
    DB 25H,7FH,6FH,00H,00H,00H,00H  ;7-9
    DB 00H,00H,00H                  ;---
    DB 3FH,7FH,53H,77H,5BH,1BH,7BH  ;A-G
    DB 3EH,12H,74H,3EH,52H,37H,37H  ;H-N
    DB 77H,1FH,2FH,3FH,6BH,18H,76H  ;O-U
    DB 76H,76H,3EH,1EH,5BH          ;V-Z

    ; ------------------------
    ;   VIDEO TELETYPE ATTRS :
    ; ------------------------

    ; VIDEO ATTRIBUTES FOR CONTEXT OF
    ; THE WRITE CHAR, IS LIKE WHEN YOU
    ; COPY THE HOMEWORK AND FOR EACH
    ; LETTER YOU WRITE IT AFTER THE BEFORE
    VIRT_ROW DB 0   ; VIDEO ROW (0AH INCREMENTS IT)
    VIRT_COL DB 0   ; VIDEO COL (0DH RESETS IT)

    ; ------------------------
    ;        CODE STARTS     :
    ; ------------------------
    RSV (400H-$) ; DATA END

    ETE DB '44'

    ; PG2:Y = STR, Z=OUT
ATOI:
    SLA %Y ; LOAD FROM PG2:Y
    CHC $48 ; CMP BY ZERO DIGIT
    TSA %C ; COMPARE
    LDC $3 ; LOAD NEGATIVE FLAG TO COMP FLAG
    PAG $.END.H ; PAGE
    BCC $.END.L ; IS NEGATIVE
    CHC $57 ; LOAD 9 DIGIT
    TSA %C ; COMPARE
    LDC $4 ; IF POSITIVE FLAG
    PAG $.END.H ; PAGE
    BCC $.END.L ; IF IS OUT OF RANGE END
    CHB $48 ; DIGIT 0
    SBB %B ; SUBS 0
    CPX ; COPY A TO X
    MVA %Z ; OUT
    CHB $10 ; LOAD 10
    MUL %B ; MUL 10
    ADC %X ; ADD NUMBER
    CPZ ; COPY TO Z
    STC ; SET COMP FLAG
    PAG $ATOI.H ; PAGE
    BCC $ATOI.L ; JUMP
.END:
    STR $RET_R ; RETURNS

    ; A=LETTER
VIDEO_TTY:
    CPZ ; COPPY ACUM IN Z
    CHC $0DH ; IMM VALUE FOR TELETYPE
    TSA %C ; COMPARES
    LDC $1 ; EQUAL FLAG
    PAG $.CR.H ; THIS FUNCTION
    BCC $.CR.L ; CARRIGE RETURN
    CHC $0AH ; IMM VALUE FOR TELETYPE
    TSA %C ; COMPARES
    LDC $1 ; EQUAL FLAG
    PAG $.LF.H ; THIS FUNCTION
    BCC $.LF.L ; NEW LINE
    LDS $VIRT_ROW ; LOAD ROW
    CHB $12 ; LOAD VALUE 12
    MUL %B ; MULTIPLY
    CPB ; COPY TO B
    LDS $VIRT_COL ; LOAD COL
    ADC %B ; ADD COLUMN
    CHC $VVIRT.L ; LOAD VIRT CON OFFSET
    ADC %C ; ADD VIRT CON OFFSET
    CPB ; SAVE OFFSET IN B
    MVA %Z ; COPY Z TO A
    PAG $MEM_B.H ; PAGE
    STA %B ; STORE
    LDS $VIRT_COL ; LOAD
    CHB $1 ; LOADS INC CONST
    ZRC ; CLEAR COMPA FLAG
    ADC %B ; INCREMENTS
    STR $VIRT_COL ; WRITES
    STR $RET_R ; RETURNS
.LF:
    LDS $VIRT_ROW ; LOAD
    CHB $1 ; LOADS INC CONST
    ZRC ; CLEAR COMPA FLAG
    ADC %B ; INCREMENTS
    CTA $VIRT_ROW.L ; WRITES
    STR $RET_R ; RETURNS
.CR:
    STR $VIRT_COL, $00H ; RESETS
    STR $RET_R ; RETURNS

    ; RESET ROUTINE OF FIRMWARE TO INITIALIZE THE
    ; BASIC HARDWARE
RST:
    STR $SP_RH, $TOS.H ; STACK HIGH
    STR $SP_RL, $TOS.L ; STACK LOW
    STR $VIRT_ROW, $0 ; RESET ROW
    STR $VIRT_COL, $0 ; RESET COL
    STR $DEV_B, $VDMEM.L ; CONFIGURE

    ; NOW THE FIRMWARE CONFIGURES THE BITMAP VIRT BY INDEX
    ; BITMAP SEGMENT COMBINATION AS A LITTLE PART OF STANDART
    ; ASCII
    PG3 $(MEM_B+VDFNT+'0').H ; PAGE
    CHA $(MEM_B+VDFNT+'0').L ; THE SPECIAL FOR THE REPRESENTABLE KEYS
    CPY ; COPY VALUE OF ACUMULATOR TO Y
    STD ; SET FLAG OF DIRECTION FOR INCREMENTS
    PG2 $MAP.H ; SET MAP IN ROM PAGE
    CHZ $MAP.L ; SET MAP IN ROM OFF
    CHB $('Z'-'0'+1) ; NUMBER OF ASCIIS
.LOOP:
    SLA %Z ; LOAD FROM ROM
    SSA %Y ; STORE TO VRAM
    MVA %B ; MOVE B VALUE
    CHC $1 ; COMPARE
    TSA %C ; TEST FOR COMP
    ZRC ; CLEAR FLAG
    SBB %C ; BECAUSE THE VALUE OF C IS SETTED USE IT FOR OPTIMIZE
    CPB ; COPY ACUMULATOR TO B
    LDC $2 ; LOAD NOT EQUAL FLAG TO COMP FLAG
    PAG $.LOOP.H ; SET PAGE
    BCC $.LOOP.L ; REPEAT

    STR $BL_RG
    
    CHZ $0
    PG2 $ETE.H
    CHA $ETE.L
    CPY
    STC
    PAG $ATOI.H
    BCC $ATOI.L
.LOO2:
    LDS $(MEM_B+KYBRD) ; READ PORT
    CHZ $0 ; LOAD 0 VALUE
    TSA %Z ; TEST A == 0
    LDC $1 ; LOAD EQUAL FLAG TO COMP FLAG
    PAG $.NATA.H ; PAGE
    BCC $.NATA.L ; NO KEY?
    STC ; SET COMP FLAG FOR JUMP ALWAYS
    STR $BL_RG ; LINK AT NEXT JMP
    PAG $VIDEO_TTY.H ; JMP PAGE
    BCC $VIDEO_TTY.L ; OFFSET AND JUMP
.NATA:
    STC ; ALWAYS JUMPS
    PAG $.LOO2.H ; LOOP PAGE
    BCC $.LOO2.L ; REPEAT LOOP

    RSV (3FF0H-$)

    ; THE NEXT CODE WILL BE HAVE A SIZE LESS
    ; THAN 16 BYTES OF MACHINE CODE THIS CODE
    ; IS AT 0FFF0H PYSHIC ADDRESS AND THE PC
    ; ON RESET JUMPS TO ITSELF
    STC ; SET COMP FLAG
    PAG $RST.H ; PAGE OF RESET
    BCC $RST.L ; JMP TO RESET
    RSV (4000H-$)