    ; KARNAL OS 0.1.1
    LOCAL 0E000H ; FIRMWARE STARTS IN E000H 
                 ; (8K ROM BEGINS EHBEBEBBE)
    
    ; CPU MAX ACCESS MEMORY LIMIT MAX IS
    ; 64K AND THE BAIOS IS IN DA EHBEHEB
    ; END OF FILE I SAY RAM, XIGL SIGA WE
    ;
    ; THE TARGET MACHINE FOR THIS FILTH IS
    ; A MACHINE. WELL WELL, IS A PC THAT HAS
    ; A DISPLAY SCREEN LIKE THE LCD MONO
    ; CALCS YES, THESE THAN IF YOU LOOK FROM
    ; A PERFECT ANGLE YOU READ THAT SAYS '8888888'
    ; HEHEHE

    ; ------------------------
    ;        EQUATES         :
    ; ------------------------

    ;---------LOGICALLY-----------
    SP_RH EQU 8000H ; SP HIGH
    SP_RL EQU 8001H ; SP LOW
    BL_RG EQU 8002H ; LINK FLAG
    RET_R EQU 8003H ; RET REG
    DBG_R EQU 8004H ; DBG REG

    ;----------DEVICES------------
    DEV_A EQU 8066H ; SNDCARD FREQ
    DEV_B EQU 8024H ; CREATES A MIRROR AT B000H-BFFF
                    ; ANY OFFSET OF PG(100H+P2,00H)
    MEM_B EQU 0B000H; MIRROR IN THE DIRECTION

    ;----------VIDEO------------
    VDFNT EQU 0D078H; D078H-D0F8H VIRT TO LED LIST TABLE
    VDPHY EQU 0D000H; D000H-D03BH LED TO LED LIST CON, D000H-D0F6H IN 19X13 HSV8
    VVIRT EQU 0D03CH; D03CH-D077H VIRT TO LED LIST CON

    ; DEFAULT VALUES OF THAT ATTRIBUTES GIVE AS RESULT A
    ; TEXT SCHEME LIKE C64 BASIC ROM REPL
    VDBGC EQU 0D0F9H; D0F9H BG COLOR, 70=DEFAULT
    VTXTC EQU 0D0FAH; D0FAH TEXT & BG2 COLOR, 75=DEFAULT
    VTXTB EQU 0D0FBH; D0FBH TEXT & BG2 BRIGH, 100=DEFAULT
    VDONS EQU 0D0FCH; D0FCH ON & BG2 SATURATION, 30=DEFAULT
    VOFFT EQU 0D0FDH; D0FDH OFF TRANSPARENCY, 70=DEFAULT
    VMODE EQU 0D0FEH; D0FEH VIDEO MODE, DEFAULT=0 (TEXT, 1=19X13 8BIT HSV 
                    ; 3 BITS FOR HUE, 3 BITS FOR BRIGHT, 2 BITS FOR SATURATION)

    LFBBI EQU 0A000H; LINEAL FRAMEBUFFER OF HSV332 OF 35X45 PIXELS SCREEN
                    ; FROM A000H-A6FFH
    LFBPX EQU 0A700H; BUFFER MMIO X
    LFBPY EQU 0A701H; BUFFER MMIO Y
    LFBPC EQU 0A702H; CURRENT PIXEL COLOR

    ; THE KEYBOARD DRIVER IT IS SOLDERED TO THE SCREEN
    ; SO THERE SHARE ADDRESSING SPACE AND IS IMPOSSIBLE
    ; TO SPLIT THE KEYBOARD FROM THE SCREEN, HEHEHEHEH
    KYBRD EQU 0D0FEH; D0FEH KEYBOARD READ

    ;----------PAPER TAPE MANIPULATOR------------

    ; ACTIONS FOR THE PTACT IS INDEXED ON THE NEXT ENUM
    ; LIST OF EQUALS
    PTCNT EQU 01H   ; GET COUNT OF STRIPS (4CM/1K PER STRIP)

    ; PAPER TAPE MANIPULATOR MMIO REGISTERS MAPED IN RAM
    ; PAGE $D1
    PTDST EQU 0D100H; SETS/GETS DESTINATION PAGE FOR MAP READABLE/WRITABLE MIRROR
    PTACT EQU 0D101H; ACTION FOR MAKE
    PTSST EQU 0D102H; SETS/GETS THE CURRENT STRIP OF TAPE
    
    ; THE DIRECTION OF CPY IS A CONVENTION AND NOT A OBLIGATORY RULE
    ; FOR THE MAPPED PAPER TAPE
    PTPAG EQU 0DBH  ; DEFAULT PAGE WHERE IS A READABLE/WRITEABLE MAP

    ; VECTORS AT FIRMWARE DATA STARTS EACH VECTOR
    ; HAS A LENGHT OF 4 BYTES (TWO INSTRUCTIONS)

    JIC $VIDEO_TTY  ; E000H :: TTY WRITE
    JIC $ATOI       ; E004H :: ATOI
    JIC $DISK_READ  ; E008H :: READ
    JIC $DRW_PIX    ; E00CH :: DRAW PIXEL
    JIC $HSV332     ; E010H :: SWITCH TO HSV332:35X45

    ; ------------------------
    ;        128B STACK     :
    ; ------------------------
STACK: RSV 128
TOS:

    ; ------------------------
    ;       LETTER MAP      :
    ; ------------------------
MAP:
    DB 77H,24H,5DH,6DH,2EH,5DH,7BH  ;0-6
    DB 25H,7FH,6FH,00H,00H,00H,00H  ;7-9
    DB 00H,00H,00H                  ;---
    DB 3FH,7FH,53H,77H,5BH,1BH,7BH  ;A-G
    DB 3EH,12H,74H,3EH,52H,37H,37H  ;H-N
    DB 77H,1FH,2FH,3FH,6BH,01H,76H  ;O-U
    DB 76H,76H,3EH,1EH,5BH,25H      ;V-Z (T P2)

    ; ------------------------
    ;   VIDEO TELETYPE ATTRS :
    ; ------------------------

    ; VIDEO ATTRIBUTES FOR CONTEXT OF
    ; THE WRITE CHAR, IS LIKE WHEN YOU
    ; COPY THE HOMEWORK AND FOR EACH
    ; LETTER YOU WRITE IT AFTER THE BEFORE
    VIRT_ROW DB 0   ; VIDEO ROW (0AH INCREMENTS IT)
    VIRT_COL DB 0   ; VIDEO COL (0DH RESETS IT)

    ; ------------------------
    ;      TEMP VARIABLES :
    ; ------------------------
    SV1 DB 0        ; SAVE

    ; ------------------------
    ;        CODE STARTS     :
    ; ------------------------
    RSV (400H-$) ; DATA END

HSV332:
    STR $VMODE, $2 ; MODE INDEX
    STR $RET_R ; RETURNS

    ; XY = POS
    ; A = PIXEL
    ;
    ; ONLY WORKS IN 35X45 HSV332
DRW_PIX:
    CPZ ; COPPY A TO Z
    MVA %X ; GET POS X
    STR $LFBPX ; SET POS X
    MVA %Y ; GET POS Y
    STR $LFBPY ; SET POS Y
    MVA %Z ; GET COLOR
    STR $LFBPC ; DRAW COLOR
    STR $RET_R ; RETURNS

    ; A=INDEX, A=AT PAGE
DISK_READ:
    STR $PTSST ; SETS STRIP
    LDS $PTDST ; READS PAGE
    STR $RET_R ; RETURNS

    ; PG2:Y = STR, Z=OUT
ATOI:
    SLA %Y ; LOAD FROM PG2:Y
    CHC $48 ; CMP BY ZERO DIGIT
    TSA %C ; COMPARE
    LDC $3 ; LOAD NEGATIVE FLAG TO COMP FLAG
    PAG $.END.H ; PAGE
    BCC $.END.L ; IS NEGATIVE
    CHC $57 ; LOAD 9 DIGIT
    TSA %C ; COMPARE
    LDC $4 ; IF POSITIVE FLAG
    PAG $.END.H ; PAGE
    BCC $.END.L ; IF IS OUT OF RANGE END
    CHB $48 ; DIGIT 0
    SBB %B ; SUBS 0
    CPX ; COPY A TO X
    MVA %Z ; OUT
    CHB $10 ; LOAD 10
    MUL %B ; MUL 10
    ADC %X ; ADD NUMBER
    CPZ ; COPY TO Z
    STC ; SET COMP FLAG
    PAG $ATOI.H ; PAGE
    BCC $ATOI.L ; JUMP
.END:
    STR $RET_R ; RETURNS

    ; A=LETTER W/ M CASE
VIDEO_TTY:
    CPZ ; COPY ACUMULATOR IN Z
    CHC $4DH ; IMM FOR M
    TSA %C ; TEST W M
    LDC $2 ; NOT EQUAL FLAG
    JIC $.NEXT1 ; NEXT
    STR $BL_RG ; LINK AT NEXT JMP
    STR $SV1 ; SAVE THE ACUM
    CHA $4EH ; LOAD N
    STC ; SET COMP FLAG
    JIC $BVIDEO_TTY ; VIDEO TTY FOR N
    LDS $SV1 ; LOAD TO ACUMULATOR
.NEXT1:
    CHC $54H ; IMM FOR T
    TSA %C ; TEST W T
    LDC $2 ; NOT EQUAL FLAG
    JIC $.NEXT2 ; NEXT
    STR $BL_RG ; LINK AT NEXT JMP
    STR $SV1 ; SAVE THE ACUM
    CHA $5BH ; LOAD T ALT
    STC ; SET COMP FLAG
    JIC $BVIDEO_TTY ; VIDEO TTY FOR N
    LDS $SV1 ; LOAD TO ACUMULATOR
.NEXT2:
    STR $BL_RG ; LINK AT NEXT JMP
    STC ; SET COMP FLAG
    JIC $BVIDEO_TTY ; PRINT CHARACTER
    LDS $VIRT_COL ; LOAD VIRT COL
    CHC $12 ; THE MAX COLS ALLOWED
    TSA %C ; TEST WITH C
    LDC $3 ; IF ITS IS GREATER THAN LINE
    JIC $.BN1 ; BOUND CHECK
    STR $BL_RG ; LINK AT NEXT JMP
    STC ; SET COMP FLAG
    CHA $0AH ; INCS LINE
    JIC $BVIDEO_TTY ; PRINT CHARACTER
    STR $BL_RG ; LINK AT NEXT JMP
    STC ; SET COMP FLAG
    CHA $0DH ; RESETS COL
    JIC $BVIDEO_TTY ; PRINT CHARACTER
.BN1:
    LDS $VIRT_ROW ; LOAD VIRT COL
    CHC $5 ; THE MAX COLS ALLOWED
    TSA %C ; TEST WITH C
    LDC $3 ; IF ITS IS GREATER THAN LINE
    JIC $.BN2 ; BOUND CHECK
    PG3 $(VDPHY-12).H ; PAGE
    CHA $(VDPHY-12).L ; DISP
    CPY ; COPY VALUE OF ACUMULATOR TO Y
    STD ; SET FLAG OF DIRECTION FOR INCREMENTS
    PG2 $VDPHY.H ; SET MAP IN ROM PAGE
    CHZ $VDPHY.L ; SET MAP IN ROM OFF
    CHB $(12*5) ; SIZE OF PAGE
.CAP1:
    SLA %Z ; LOAD FROM ROM
    SSA %Y ; STORE TO VRAM
    MVA %B ; MOVE B VALUE
    CHC $1 ; COMPARE
    TSA %C ; TEST FOR COMP
    ZRC ; CLEAR FLAG
    SBB %C ; BECAUSE THE VALUE OF C IS SETTED USE IT FOR OPTIMIZE
    CPB ; COPY ACUMULATOR TO B
    LDC $2 ; LOAD NOT EQUAL FLAG TO COMP FLAG
    PAG $.CAP1.H ; SET PAGE
    BCC $.CAP1.L ; REPEAT
.BN2:
    STR $RET_R ; RETURNS

    ; A=LETTER
BVIDEO_TTY:
    CPZ ; COPPY ACUM IN Z
    CHC $0DH ; IMM VALUE FOR TELETYPE
    TSA %C ; COMPARES
    LDC $1 ; EQUAL FLAG
    PAG $.CR.H ; THIS FUNCTION
    BCC $.CR.L ; CARRIGE RETURN
    CHC $0AH ; IMM VALUE FOR TELETYPE
    TSA %C ; COMPARES
    LDC $1 ; EQUAL FLAG
    PAG $.LF.H ; THIS FUNCTION
    BCC $.LF.L ; NEW LINE
    LDS $VIRT_ROW ; LOAD ROW
    CHB $12 ; LOAD VALUE 12
    MUL %B ; MULTIPLY
    CPB ; COPY TO B
    LDS $VIRT_COL ; LOAD COL
    ADC %B ; ADD COLUMN
    CHC $VVIRT.L ; LOAD VIRT CON OFFSET
    ADC %C ; ADD VIRT CON OFFSET
    CPB ; SAVE OFFSET IN B
    MVA %Z ; COPY Z TO A
    PAG $VVIRT.H ; PAGE
    STA %B ; STORE
    LDS $VIRT_COL ; LOAD
    CHB $1 ; LOADS INC CONST
    ZRC ; CLEAR COMPA FLAG
    ADC %B ; INCREMENTS
    STR $VIRT_COL ; WRITES
    STR $RET_R ; RETURNS
.LF:
    LDS $VIRT_ROW ; LOAD
    CHB $1 ; LOADS INC CONST
    ZRC ; CLEAR COMPA FLAG
    ADC %B ; INCREMENTS
    CTA $VIRT_ROW.L ; WRITES
    STR $RET_R ; RETURNS
.CR:
    STR $VIRT_COL, $00H ; RESETS
    STR $RET_R ; RETURNS

    ; RESET ROUTINE OF FIRMWARE TO INITIALIZE THE
    ; BASIC HARDWARE
RST:
    STR $SP_RH, $TOS.H ; STACK HIGH
    STR $SP_RL, $TOS.L ; STACK LOW
    STR $VIRT_ROW, $0 ; RESET ROW
    STR $VIRT_COL, $0 ; RESET COL
    STR $DEV_B, $VDMEM.L ; CONFIGURE

    ; NOW THE FIRMWARE CONFIGURES THE BITMAP VIRT BY INDEX
    ; BITMAP SEGMENT COMBINATION AS A LITTLE PART OF STANDART
    ; ASCII
    PG3 $(VDFNT+'0').H ; PAGE
    CHA $(VDFNT+'0').L ; THE SPECIAL FOR THE REPRESENTABLE KEYS
    CPY ; COPY VALUE OF ACUMULATOR TO Y
    STD ; SET FLAG OF DIRECTION FOR INCREMENTS
    PG2 $MAP.H ; SET MAP IN ROM PAGE
    CHZ $MAP.L ; SET MAP IN ROM OFF
    CHB $('Z'-'0'+2) ; NUMBER OF ASCIIS
.LOOP:
    SLA %Z ; LOAD FROM ROM
    SSA %Y ; STORE TO VRAM
    MVA %B ; MOVE B VALUE
    CHC $1 ; COMPARE
    TSA %C ; TEST FOR COMP
    ZRC ; CLEAR FLAG
    SBB %C ; BECAUSE THE VALUE OF C IS SETTED USE IT FOR OPTIMIZE
    CPB ; COPY ACUMULATOR TO B
    LDC $2 ; LOAD NOT EQUAL FLAG TO COMP FLAG
    PAG $.LOOP.H ; SET PAGE
    BCC $.LOOP.L ; REPEAT

    ; NEXT TO THAT WE HAVE TO CONFIGURE THE PAPER TAPE
    ; MANIPULATOR
    STR $PTDST, $PTPAG ; SETS THE PAGE OF PAPER TAPE
    STR $PTSST, $0 ; STRIP 0
IDLE_LOOP:
.LOO2:
    LDS $KYBRD ; READ PORT
    CHZ $0 ; LOAD 0 VALUE
    TSA %Z ; TEST A == 0
    LDC $1 ; LOAD EQUAL FLAG TO COMP FLAG
    PAG $.NATA.H ; PAGE
    BCC $.NATA.L ; NO KEY?
    CHZ $1 ; LOAD UP VALUE
    TSA %Z ; TEST A == UP ARROW
    LDC $1 ; LOAD EQUAL FLAG TO COMP FLAG
    PAG $LAUNCH.H ; PAGE
    BCC $LAUNCH.L ; NO KEY?
    STC ; SET COMP FLAG FOR JUMP ALWAYS
    STR $BL_RG ; LINK AT NEXT JMP
    PAG $VIDEO_TTY.H ; JMP PAGE
    BCC $VIDEO_TTY.L ; OFFSET AND JUMP
.NATA:
    STC ; ALWAYS JUMPS
    PAG $.LOO2.H ; LOOP PAGE
    BCC $.LOO2.L ; REPEAT LOOP

    ; LAUNCHER FOR THE DOWN ARROW THAT ON PRESS IT THE 1ST STRIP
    ; OF PAPER TAPE WILL BE LOAD AT 1800H-1C00H
LAUNCH:
    STR $PTSST, $0 ; SETS STRIP
    LDS $PTDST ; READS PAGE
    CPW ; COPY THE PAGE TO PG2 (W)
    CHA $0H ; OFFSET IN PG2
    CPY ; COPY TO Y
    PG3 $18H ; ADDRESS 1800H
    CHZ $0H ; OFFSET IN PG3
    CHB $4 ; NUMBER OF PAGES
.LOOP:
    CHA $0FFH ; THE MAX INDEX OF PAGES
    CPX ; COPY TO X
.SUBLOOP:
    SLA %Z ; LOAD FROM ROM
    SSA %Y ; STORE TO VRAM
    MVA %X ; MOVE B VALUE
    CHC $0 ; COMPARE
    TSA %C ; TEST FOR COMP
    CHC $1 ; NEXT VALUE
    ZRC ; CLEAR FLAG
    SBB %C ; BECAUSE THE VALUE OF C IS SETTED USE IT FOR OPTIMIZE
    CPX ; COPY ACUMULATOR TO B
    LDC $2 ; LOAD NOT EQUAL FLAG TO COMP FLAG
    PAG $.SUBLOOP.H ; SET PAGE
    BCC $.SUBLOOP.L ; REPEAT
    MVA %B ; MOVE THE B REGISTER
    CHC $0 ; ZERO IF NON
    TSA %C ; COMPARE
    CHC $1 ; LOAD VALUE
    SBB %C ; OPERATE
    CPB ; COPY TO B
    LDC $2 ; LOAD NOT EQUAL FLAG TO COMP FLAG
    PAG $.LOOP.H ; SET PAGE
    BCC $.LOOP.L ; REPEAT
    STC ; SET COMP FLAG
    JIC $1800H ; JUMP TO ADDRESS

    RSV (1FF0H-$)

    ; THE NEXT CODE WILL BE HAVE A SIZE LESS
    ; THAN 16 BYTES OF MACHINE CODE THIS CODE
    ; IS AT 0FFF0H PYSHIC ADDRESS AND THE PC
    ; ON RESET JUMPS TO ITSELF
    STC ; SET COMP FLAG
    PAG $RST.H ; PAGE OF RESET
    BCC $RST.L ; JMP TO RESET
    RSV (2000H-$)